services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: subscriptions
    ports:
      - "33306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 2s
      timeout: 2s
      retries: 20
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  subscriptions:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      HTTP_PORT: 8080
      GRPC_PORT: 9090
      MYSQL_DSN: root:root@tcp(mysql:3306)/subscriptions?parseTime=true
      LOG_LEVEL: info
      APP_API_KEY: subscriptions-app-api-key
      AUTH_SERVICE_GRPC_ADDR: host.docker.internal:38083
      APP_SERVICE_NAME: subscriptions-service
    ports:
      - "38080:8080"
      - "39090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      mysql:
        condition: service_healthy
